//
// Created by vertr on 04/05/2024.
//

#ifndef SEGUNDO_PARCIAL_SEGUNDOEJERCICIOJEFFERSONSOTO_H
#define SEGUNDO_PARCIAL_SEGUNDOEJERCICIOJEFFERSONSOTO_H


class SegundoEjercicioJeffersonSoto {

};


#endif //SEGUNDO_PARCIAL_SEGUNDOEJERCICIOJEFFERSONSOTO_H
